version: '3.7'
x-shared-envs:
    &shared-envs
    MONGODB_URL: mongodb://database:27017
    KID: kid-123
services:
    auth-service:
        build:
          context: ./
        command: sh -c "dockerize -wait tcp://database:27017 npm run auth-service"
        depends_on:
            - database
        environment: *shared-envs
        ports:
            - 49876:8080
            - 9228:9228
        volumes:
            - ./src/auth-service:/home/node/src/auth-service
    database:
        image: mongo:4.2.1
        ports:
            - 49875:27017
    downstream-service:
        build:
          context: ./
        command: sh -c "dockerize -wait tcp://database:27017 -wait tcp://auth-service:8080 npm run downstream-service"
        depends_on:
            - auth-service
            - database
        environment:
            << : *shared-envs
            JWKS_ENDPOINT: http://auth-service:8080/.well-known/jwks.json
        ports:
            - 49877:8080
            - 9227:9227
        volumes:
            - ./src/downstream-service:/home/node/src/downstream-service