version: '3.7'
services:
    webserver:
        build:
          context: ./
        command: sh -c "dockerize -wait tcp://database:27017 npm start"
        depends_on:
            - database
        environment:
            - MONGODB_URL=mongodb://database:27017
            - PRIVATE_KEY=example_private_key
        ports:
            - 49876:8080
        volumes:
            - ./src:/json-web-tokens/src
    database:
        image: mongo:4.2.1
        ports:
            - 49875:27017
